spring.application.name=devjourney

# PostgreSQL Config

spring.datasource.url=jdbc:postgresql://localhost:5432/developer_journal
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA config

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ThisIsAVeryLongSecretKeyForDevelopmentOnly123456789
jwt.expiration=86400000